version: '3.9'
services:
  db:
    image: postgres:14
    container_name: my-postgres
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - my-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "mydb", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  my-db-data: